### ISSUE TITLE
.searchParams property

### ISSUE THREAD

**Issue by simevidas** [WebReflection/url-search-params#1]
Firefox also implements a `.searchParams` property on anchors; [demo](http://jsbin.com/qiwoce/edit?html,js,console). Maybe you can polyfill that via a `HTMLAnchorElement.prototype.searchParams` getter. 

Btw, I wasn’t able to find in the URL spec where it says that anchors implement that API.

**Comment by WebReflection** [comment]
good idea, will have a look

**Comment by WebReflection** [comment]
this enhancement has been introduced in version `0.2.0`
However, as it has been explained in here:
https://github.com/WebReflection/url-search-params#about-htmlanchroelementprototypesearchparams

there are browsers where this polyfill cannot possibly work. Opera, and GNOME Web based on Webkit and others are just few examples where either there are no getters and setters exposed as `search` or even `href` or these are attached as own properties per each link creation.

Right now these cannot possibly be fixed, so I've written the needed check which reflects Firefox behavior.

Right now I hope this is enough, feel free to close if there are problems in supported browsers.
Thank you

**Comment by RReverser** [comment]
@WebReflection `URL.prototype.searchParams` should be also polyfilled, but currently doesn't seem to be. Would you reopen this issue or better to raise another one?

**Comment by WebReflection** [comment]
better a new one, thanks
