### ISSUE TITLE
Does not seem to work on Edge or IE 11

### ISSUE THREAD

**Issue by rajsite** [WebReflection/url-search-params#10]
![capture](https://cloud.githubusercontent.com/assets/1588923/18299319/596c3f28-7485-11e6-9674-fe1972aafa3b.PNG)

Edit: Using the latest v0.6 :)

**Comment by WebReflection** [comment]
please confirm it's fixed and, if that's the case, close this.

Thank you

**Comment by rajsite** [comment]
Sorry for the terseness of the issue when created, looking back it wasn't the best report.

Used 0.6.1 in IE11 and Edge and seems to work great! thanks @dartess and @WebReflection!
