### ISSUE TITLE
how i can build this

### ISSUE THREAD

**Issue by sergey-kozlov** [WebReflection/url-search-params#11]
Hi. I found a flaw in your project. I was able to fix it, but I can not build the project on my computer. What do I need to do before sending the PR?

Sorry for my bad english.

**Comment by WebReflection** [comment]
`npm install`
`make`
that's pretty much it

**Comment by sergey-kozlov** [comment]
Thank. I think I need Linux or Mac for this.

**Comment by WebReflection** [comment]
yes, I guess that's true for pretty much everything NodeJS related.

Or, you can use Bash for windows, that would work too.
