### ISSUE TITLE
ES6 import?

### ISSUE THREAD

**Issue by louh** [WebReflection/url-search-params#14]
Is there a way to do this via an ES6 import? e.g.

```js
import 'url-search-params'
// Expect window.URLSearchParams to exist
```

**Comment by WebReflection** [comment]
you want an import that pollutes the global context ... not sure that's ideal.

Just use the regular file and keep it outside your build system. Polyfills should be easy to remove requiring zero effort, having it as explicit ES6 dependency that pollutes the global scope and context doesn't seem a good solution/pattern.

**Comment by louh** [comment]
You're right to be hesitant about polluting global context -- I share that concern as well.

However, I've seen this pattern implemented for other polyfills for native browser functionality. See GitHub's polyfill for `window.fetch`, [for example](https://github.com/github/fetch), which is a [global import](https://github.com/github/fetch#installation). This allows my module to "assume" a modern browser environment and call `window.fetch()` without needing to check whether `fetch()` is locally imported or in the global scope.

So, I think this pattern is also beneficial for `URLSearchParams`, which Firefox and Chrome implement natively in the global context. However, I want to use your polyfill only for browsers that don't implement natively, and fall back on native implementation whenever possible. By `require()`ing the polyfill directly, I would need to perform a check and import the polyfill in every module that needs to use it -- which results in a several instances of duplicate boilerplate.

In my ideal scenario, I would only need to `import 'url-search-params'` one time, at the top level of my module hierarchy. The rest of my application can now simply assume that it exists "natively" whether it does or not. When browser support becomes much more consistent, I only need to remove the initial import statement and the dependency in `package.json` -- much less effort than the alternative.

I hope that makes sense and please let me know if you had another idea in mind.

**Comment by WebReflection** [comment]
> This allows my module to "assume" a modern browser environment and call window.fetch() without needing to check whether fetch() is locally imported or in the global scope.

that's what I also do with eveyr polyfill of mine. I don't need an ES6 module for that though, it's external my dependencies tree and eventually static on the page template.

Try to imagine I've been writing polyfills for the last 15 years and I kinda know how these work ;-)


> In my ideal scenario, I would only need to import 'url-search-params' one time, at the top level of my module hierarchy.

I think you need to import top level of your page, because it has nothing to do with your module hierarchy.

Modules work like this: you need something, you import it.

Assuming stuff is included on the top-level module, unless this is imported everywhere as a module that exports itself all its dependencies, is also a bad pattern.

You don't want to include and assume anything, you just want to use `URLSearchParams`.

Good, the way to do that, is to incldue as script on the top level of your page this polyfill and forget about it until the day you'll remove it from the top level of your page.

**Comment by WebReflection** [comment]
P.S.

> However, I've seen this pattern implemented for other polyfills for native browser functionality. See GitHub's polyfill for window.fetch, for example, which is a global import. 

I don't like their solution, feel free to fork this repo if you think that's a good way to include global dependencies in ES6.

This is about [ponyfill](https://ponyfoo.com/articles/polyfills-or-ponyfills#ponyfills) VS [polyfill](https://ponyfoo.com/articles/polyfills-or-ponyfills#polyfills-or-ponyfills) and in latter case, I believe ES6 modules are not the right way to go.

Apologies if this is not the answer you were looking for.

**Comment by louh** [comment]
No worries, I can pollute the global namespace manually :) We have different needs and in our particular application this method works fine, for now. Thanks for your explanation.

**Comment by indiesquidge** [comment]
@louh, [this may be what you're looking for](https://github.com/jerrybendy/url-search-params-polyfill)

**Comment by yvele** [comment]
Why not providing an explicit polyfill endpoint like `url-search-params/polyfill`?

Here is an example of a potential Webpack usage (exactly like `@babel/polyfill` or any `core-js` polyfill):

```js
{
  entry : [
    "@babel/polyfill",
    "core-js/fn/array/flat-map",
    "url-search-params/polyfill", // <-------- HERE
    "src/main.js"
  ]
}
```

The repository https://github.com/jerrybendy/url-search-params-polyfill looks redundant and with less quality to me 🤔 I don't want to use "only" to have proper `window` polyfills.
