### ISSUE TITLE
support for phantomjs

### ISSUE THREAD

**Issue by mh-cbon** [WebReflection/url-search-params#15]
Hi,

I can t get it working in phantomjs.

It appears URL.prototype.search is not set, so at [that](https://github.com/WebReflection/url-search-params/blob/master/src/utilities.js#L64) line, the test won t jump in and the upgrade won t occur.

I m a bit loss in this prototype thing upgrade. Can you suggest something ?

thanks !

**Comment by WebReflection** [comment]
it's probably a non configurable issue with the old WebKit engine

**Comment by WebReflection** [comment]
closing this as Phantom JS is half-death project.
