### ISSUE TITLE
Constructor does not support all signatures defined by the spec.

### ISSUE THREAD

**Issue by serhalp** [WebReflection/url-search-params#17]
In the `URLSearchParams` spec, the [constructor supports empty arguments, a string, a sequence (e.g. array), or a record (e.g. object)](https://url.spec.whatwg.org/#concept-urlsearchparams-new).

This implementation [only supports the first two forms](https://github.com/WebReflection/url-search-params/blob/c2d8c48/src/url-search-params.js#L14-L36).

This should either be implemented or clearly documented as unsupported. Currently the README links to the MDN documentation which [also lists all these constructor signatures](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/URLSearchParams).

I could take a stab at a PR if it would be accepted.

**Comment by WebReflection** [comment]
I'll have a look, thanks

**Comment by WebReflection** [comment]
fixed `0.7.0`

**Comment by serhalp** [comment]
Wow, that was almost too quick. Thank you!
