### ISSUE TITLE
sort()

### ISSUE THREAD

**Issue by stevenvachon** [WebReflection/url-search-params#19]
is missing

**Comment by WebReflection** [comment]
not in here: https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams

and not even a link provided to the API method ... I don't think that's the best way to file a bug Steven.

I won't move a finger 'till I have something more to think about.

Regards

**Comment by stevenvachon** [comment]
MDN is way outdated and should not be your point of reference. Please use the spec: https://url.spec.whatwg.org

**Comment by WebReflection** [comment]
please file reasonable bugs or you'll be ignored.

**Comment by stevenvachon** [comment]
Idiot.

**Comment by ljharb** [comment]
mdn is a wiki; if you believe it to be outdated, please update it yourself.
