### ISSUE TITLE
URLSearchParams.prototype.sort() is missing

### ISSUE THREAD

**Issue by felixfbecker** [WebReflection/url-search-params#22]
The method is defined in the spec here: https://url.spec.whatwg.org/#interface-urlsearchparams

> The sort() method, when invoked, must run these steps:
> 
> Sort all name-value pairs, if any, by their names. Sorting must be done by comparison of code units. The relative order between name-value pairs with equal names must be preserved.
> 
> Run the update steps.

The method is currently missing.

**Comment by WebReflection** [comment]
What's the use case for this?
I've tons of things to do and beside having 100% specs compliant API I'd like to know how important it is for a better estimation, thanks

**Comment by felixfbecker** [comment]
I saw it as a blocker for jsdom/whatwg-url adoption, but sounds like that is not going to happen anyway. Mainly wanted to have a proper issue for this open so this is visible for users.

**Comment by WebReflection** [comment]
Also, this is absolutely unfair after all the contribution to specs compliant polyfill I've done for 16 years.

https://github.com/jsdom/whatwg-url/issues/37#issuecomment-298365447

And after someone insulting me I end up being the one with an attitude?

What the hell is wrong with Donenic !

**Comment by WebReflection** [comment]
> sounds like that is not going to happen anyway

Where did you read that?

I just said it's not on my priority list 'cause I've never needed it.

It looks like Domenic will ever accept anything from me but that's an issue for jsdom, not an issue for this poly.

**Comment by felixfbecker** [comment]
> > sounds like that is not going to happen anyway
>
> Where did you read that?

That's just the impression I got from https://github.com/jsdom/whatwg-url/issues/37#issuecomment-298365447

I don't want to take any side here, I hope you understand that. I think it would be awesome for the community if we all worked together to fix what needs to be fixed and get this into jsdom/whatwg-url, but I am not in the position to make this happen.

**Comment by WebReflection** [comment]
Until the community tolerates [these kind of developers](https://github.com/WebReflection/url-search-params/issues/19#issuecomment-294951194) and **I** get the blame for someone with an attire toward standards I've advocated and promoted a lifetime, I think we have way more important things to solve as community.

**Comment by WebReflection** [comment]
btw, apparently not a single browser is implementing this `.sort` method but I'd like to compare my implementation with some native one. Any idea which/when browsers will have it?

**Comment by felixfbecker** [comment]
No, sorry.

**Comment by felixfbecker** [comment]
Node 7 has is implemented:
```js
> require('url').URLSearchParams.prototype
URLSearchParams {
  append: [Function: append],
  delete: [Function: delete],
  get: [Function: get],
  getAll: [Function: getAll],
  has: [Function: has],
  set: [Function: set],
  sort: [Function: sort],
  entries: [Function: entries],
  forEach: [Function: forEach],
  keys: [Function: keys],
  values: [Function: values],
  toString: [Function: toString] }
```

**Comment by WebReflection** [comment]
in my node 7.2.1 this returns undefined
`require('url').URLSearchParams`

anyway, I'll try to update the poly with a simple sort implementation first and see how it goes.

At the end, if the goal is to be consistent with the browser cache results (which is the use case I was missing) it looks like it doesn't matter as long as items are sorted consistently every single time so that a simple `keys.sort()` should do, without going nuts with code points that might require an extra polyfill in.

I will compare results this evening and see what's the outcome.

**Comment by felixfbecker** [comment]
I am running Node 7.7.0

**Comment by WebReflection** [comment]
will try that out this evening. Thanks
