### ISSUE TITLE
Option not to fall back to browser version?

### ISSUE THREAD

**Issue by mockdeep** [WebReflection/url-search-params#24]
On versions of Firefox from 29 to 43, there is partial support for `URLSearchParams`, but not complete support. The result for us is that when using this polyfill our site works on Firefox 28 and before, and 44 and after, but not on the versions in between, due to the fact that the library falls back to the browser version if it exists. For these cases, it would be nice to have a way to import this and override the browser implementation, rather than falling back.

https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams#Browser_compatibility

**Comment by WebReflection** [comment]
> when using this polyfill our site works on Firefox 28 and before, and 44 and after

awesome, I have't tested FF to much I'm actually happy it works for the old one and the latest.


Do you mind elaborating a bit about what's actually broken or not present in there?

Forcing a poly over partial support is, in my experience, not the best way to go when it's possible to just add a method like it might be in that FF case between 29 and 43 included.

Thanks for any extra detail.

**Comment by mockdeep** [comment]
Sure, so we're seeing the following error:

```
TypeError: search[Symbol.iterator] is not a function
```

In line with the browser compatibility listing, it looks like the search params are not iterable. It looks like our code is just trying to map it to a plain object, so I'd imagine we can work around it somehow on our end in a pinch. Our source code:

```js
    getSearchParams: function () {
      const search = new URLSearchParams(this.getSearch().substring(1));
      const params = {};

      /* ▼▼▼▼▼▼▼▼the error occurs on the line below ▼▼▼▼▼▼▼▼ */
      for (const entry of search) {
        const [key, value] = entry;
        params[key] = value;
      }

      return params;
    },
```

And the compiled source after `babel`:

```js
    getSearchParams: function getSearchParams() {
      var search = new URLSearchParams(this.getSearch().substring(1));
      var params = {};

      var _iteratorNormalCompletion = true;
      var _didIteratorError = false;
      var _iteratorError = undefined;

      try {
        /* ▼▼▼▼▼▼▼▼the error occurs on the line below ▼▼▼▼▼▼▼▼ */
        for (var _iterator = search[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
          var entry = _step.value;

          var _entry = _slicedToArray(entry, 2),
              key = _entry[0],
              value = _entry[1];

          params[key] = value;
        }
      } catch (err) {
        _didIteratorError = true;
        _iteratorError = err;
      } finally {
        try {
          if (!_iteratorNormalCompletion && _iterator.return) {
            _iterator.return();
          }
        } finally {
          if (_didIteratorError) {
            throw _iteratorError;
          }
        }
      }

      return params;
    }
```

**Comment by WebReflection** [comment]
Please let me know how it goes with `v0.9.0`, thank you.

**Comment by mockdeep** [comment]
Wow, that was quick! Thanks, I'll give it a look shortly.

**Comment by mockdeep** [comment]
Yep, just tested it on Browserstack and looks like that did the trick. Thanks so much!

**Comment by WebReflection** [comment]
Np

**Comment by halkeye** [comment]
As a user. YAY!

As a sauce labs employee, we offer open source accounts! https://saucelabs.com/opensource (scroll to the bottom)
