### ISSUE TITLE
Unfortunally "delete" is a reserved word for older browser (eg. Safari 5.0.3)

### ISSUE THREAD

**Issue by bitmarte** [WebReflection/url-search-params#25]
If you want to use this polyfill on older browsers we need to change the way to access at some properties that are reserved word, unfortunately.

I fixed it on my local branch, so I will propose a pull request on this issue.

Eg.
on modern browser = a.delete
on older browser (eg. Safari 5.0.3) = a['delete']

**Comment by WebReflection** [comment]
It's a mater of minifier, but uglify-js 1 with IE8 options seems so 2010 and no toolchain these days patch/target down to iOS 5 or IE8 anymore.

This repo is fairly stable though, so feel free to fork and minify with such old version of uglify

**Comment by WebReflection** [comment]
Actually, it's already using uglify 1 ... I'll see how different is the minified result and switch IE8 flags on and publish, if not so different.

**Comment by bitmarte** [comment]
Could you try to use uglify2?

**Comment by WebReflection** [comment]
no no, uglify-1 is just fine

**Comment by bitmarte** [comment]
Also facebook use some older reserved keywords and mishoo fixed his project from 2.4.16 version.
Take a look here: https://github.com/mishoo/UglifyJS2/issues/534

**Comment by WebReflection** [comment]
`0.10` should work in IE8 too

**Comment by bitmarte** [comment]
Thank you, great job!
If you take a look at compressed result you could see the changes (from **a.delete** to **a['delete']** ), as we aspected.

**Comment by WebReflection** [comment]
if you take a look at gzip final output size you can also see it's now 2KB instead of 1.6KB :sob: 

Anyway ... to make it work in IE8 it's not just syntax, you need most of ES5 and some ES2015 (Symbol)

**Comment by bitmarte** [comment]
Yes, I know.
Another change is to produce an additional file at build time (eg. "build/url-search-params.ie8.js") and mention it on readme.md just for older browsers support.

If you want to use it on older browsers you need to pay something :smile:

**Comment by WebReflection** [comment]
[tell me about it](https://github.com/WebReflection/ie8)
