### ISSUE TITLE
URL.prototype.searchParams should be polyfilled

### ISSUE THREAD

**Issue by RReverser** [WebReflection/url-search-params#3]
`URL.prototype` pretty much reflects `HTMLAnchorElement.prototype` on web platform, so, as a continuation of #1, FF implements not only `HTMLAnchorElement.prototype.searchParams` but also `URL.prototype.searchParams`, and I beleive this polyfill should shim it as well.

**Comment by WebReflection** [comment]
version 0.3.0 adds `searchParams` to the URL too in case is not available.

**Comment by RReverser** [comment]
Thanks!
