### ISSUE TITLE
Polyfill doesn't work because of strict mode.

### ISSUE THREAD

**Issue by Li0liQ** [WebReflection/url-search-params#31]
As the polyfill uses [`'use strict'`](https://github.com/WebReflection/url-search-params/blob/master/build/url-search-params.node.js#L23), it fails to assign value to 
`URLSearchParams` in [url-search-params.node.js#L174](https://github.com/WebReflection/url-search-params/blob/master/build/url-search-params.node.js), because it is not allowed to implicitly create global variables in strict mode.

**Comment by WebReflection** [comment]
URLSearchParams is a function of that scope, not a global reference.
