### ISSUE TITLE
%2B parsed to space unexpected on iOS 10.3

### ISSUE THREAD

**Issue by macdao** [WebReflection/url-search-params#32]
`new URLSearchParams('q=%2B').get('q')` should return `+`(iOS 11 or Chrome or else), but it returns space (` `) on iOS Safari 10.3. It caused a bug on my project.

iOS Safari 10.3 support URLSearchParams however with this bug. I know it's not url-search-params' issue but it is a issue when i'm using URLSearchParams.

I resolved this by add string replace ` ` with `+` after I get `q` (see above). It's tricky.

Any idea to resolve this issue gracefully?

Thanks.

**Comment by WebReflection** [comment]
does iOS 10.3 returns a space when you do this? `decodeURIComponent('%2B')` ?

**Comment by macdao** [comment]
`decodeURIComponent('%2B')` returns `+` on iOS 10.3

**Comment by WebReflection** [comment]
then it looks like a very specific iOS 10 bug and I wonder if you could simply go this way:

```html
<script>
try {
  if (new URLSearchParams('q=%2B').get('q') !== '+') throw {};
} catch(e) {
  window. URLSearchParams = null;
}
</script>
<script src="thispolyfill.js"></script>
```

**Comment by WebReflection** [comment]
actually maybe I can do that in the file itself ... it's just that I don't know if it's a good idea to fully replace that broken native instead of acknowledging its defects

**Comment by macdao** [comment]
I have no idea also. While the fact is there are (at least one on iOS 10.3) broken native URLSearchParams implementations.

Leave the option to user may make someone else fall into the trap which took me days to identify the reason.

At least this issue page may help someone.

**Comment by macdao** [comment]
I would like to provide more information.

according to this: <http://docs.w3cub.com/browser_support_tables/urlsearchparams/> iOS do not support URLSearchParams before 10.3 and 10.3 is proved to be defective, while 11.3 is tested and it is fine.

**Comment by fwchen** [comment]
awesome
