### ISSUE TITLE
umd support

### ISSUE THREAD

**Issue by taoqf** [WebReflection/url-search-params#33]
Are we plan support `umd`?
and support webpack and babel?
seems we should add `module` field in package.json.

**Comment by WebReflection** [comment]
this is a polyfill, not a module.

Please follow these instructions to safely and conditionally include it in your pages:
https://github.com/WebReflection/url-search-params#ios-10--other-platforms-bug

**Comment by taoqf** [comment]
Allright alright.But I do really need these.
