### ISSUE TITLE
doesn't work in IE11

### ISSUE THREAD

**Issue by eldyvoon** [WebReflection/url-search-params#37]
worked in Edge but not IE11

**Comment by WebReflection** [comment]
That is not true.

This is IE11
<img width="396" alt="screen shot 2018-09-10 at 11 06 15" src="https://user-images.githubusercontent.com/85749/45287853-9c739400-b4e9-11e8-8ace-b9ce1358bba3.png">

and this is the test page:
http://webreflection.github.io/url-search-params/test/
