### ISSUE TITLE
Polyfill problem in Edge 41.16299.371.0

### ISSUE THREAD

**Issue by jaapster** [WebReflection/url-search-params#42]
In Edge 41.16299.371.0, the polyfill seems to not create the global URLSearchParams object.

"URLSearchParams is not defined"

In Edge 42.17134.1.0 the problem does not occur.

**Comment by WebReflection** [comment]
not only this is a duplicate, but I have no page to test, no details on how you load the polyfill, and on top of that, no Edge 41 ... how do you think I can help with this report?

**Comment by WebReflection** [comment]
maybe it's 'cause GitHub has issues right now but a comment rather than just closing would help me even further understanding what's going on, thanks.

**Comment by jaapster** [comment]
The duplicate is because my first attempt at submitting the issue disappeared from github.

I will try and create an example to replicate the issue for you.

**Comment by jaapster** [comment]
I just posted a reply to this, but that vanished too.

I will try and create an example replicating this issue.

**Comment by jaapster** [comment]
Hi Andrea,

Apologies for the duplicate. When I look in github, the issues I posted have disappeared. That’s why I posted the issues twice.

I will try and create a testpage for you.

What do you mean with no Edge 41 by the way?

Best regards,

Jaap

**Comment by jaapster** [comment]
Come to think of it,

if you have no Edge 41, you will never be able to reproduce the issue of course.

So you will not be able to help me or fix this issue.

**Comment by WebReflection** [comment]
So, PR welcome ?

**Comment by WebReflection** [comment]
I've still no idea how you are loading this library though, not much I can do with this issue.

**Comment by jaapster** [comment]
I'm loading the polyfill using webpack.

`entry: {
	core: [
		'./src/polyfills',
		'@babel/polyfill',
		'./src/index.js'
	]
}`

The package is imported in polyfills.js

`
import 'event-source-polyfill';
import 'custom-event-polyfill';
import 'url-search-params';
`

After some experimenting, I found out that if, in the package code, 'URLSerachParams' is declared in 'window' explicitely, the problem does not occur.

**Comment by WebReflection** [comment]
There you go. I think you are experiencing something already described in the README.
https://github.com/WebReflection/url-search-params#ios-10--other-platforms-bug

On top of that, you are importing with a bundler without addressing the module.

```js
import URLSearchParams from 'url-search-params';
```
